### ISSUE TITLE
Filter the selected "From" datasource out of the "To" list

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#10]
No need to support x-to-x mapping, so we could help make the UI more intuitive and less cluttered by simply removing the selected "From" datasource out of the "To" list.

**Comment by bdemchak** [comment]
I agree, and thought of that, too. The dynamics of making that happen would probably not be worth the trouble, though. Your choice ...

**Comment by AlexanderPico** [comment]
Ah, we should actually not do this particular filtering because of another planned enhancement (issue yet to be added) to allow multi-select in the "FROM" and for the "TO" list to still contain those selections. E.g., I use ID mapping often to convert a mixed column of Ensembl and Entrez ID to a new column of just Ensembls.
