### ISSUE TITLE
Dump table file with all mapping details

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#12]
Dump a .csv file that contains all the details of the mapping:
- "from" column, "to" column (list), to column (single)
- include both "to" columns regardless of UI selection
- summary of mapping at top of file

Include link to file in dialog, e.g., "see details"

**Comment by AlexanderPico** [comment]
For now, this informations (even the non-mapped results) are available in the Node Table to the user. They can pull it out into Excel or whatever they please.

**Comment by AdamStuart** [comment]
Should be a table browser feature
