### ISSUE TITLE
Integrate mapping function in to Import Dialogs

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#13]
Maybe offer an expandable section in the import dialog that collected tunable values to pass onto Node Table mapper after import is complete?

**Comment by AlexanderPico** [comment]
Let's maybe wait until we have post-import table -to-network mapping implemented in Cytoscape via Toronto's data panel idea. Then, this import-then-map-then-key process would just work.

**Comment by AdamStuart** [comment]
Closing. This is best included as part of other work on import.
