### ISSUE TITLE
QC Checks

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#15]
- [x] title of jar file (should be idmapper-1.0.0)
- [x] title displayed in app manager (should be ID Mapper)
- [x] version displayed in app manager (should be 1.0.0)
- [ ] prep for submission process for core app (what is the process?)
- [x] menu item label (should be "Map column")

**Comment by AlexanderPico** [comment]
version is app manager is currently "0"

<img width="649" alt="screen shot 2016-09-15 at 12 29 40 pm" src="https://cloud.githubusercontent.com/assets/1418193/18564987/d689b2b0-7b42-11e6-91cb-8d4b225aa53d.png">

**Comment by AdamStuart** [comment]
Do you know what’s going on here?
The version is in the POM and shows up in the jar title.

Adam

**Comment by AdamStuart** [comment]
> > menu item label (should be "Map column")
> > AFAIK, because it leads to a modal dialog, it should have an ellipsis
