### ISSUE TITLE
Result dialog

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#16]
This is looking great, just a minor point. In addition to listing when one-to-many is detected, we should also have a line that reflects the user choice to 'force single' or not. Otherwise, it seems like the selection was ignored and one-to-many results were included in new column.

**Comment by AdamStuart** [comment]
Do you mean in the dialog box that shows results, or in the header of the new column?

**Comment by AlexanderPico** [comment]
the result. This one, for example, makes is seem like I got one-to-many results even though I checked "force single"
<img width="415" alt="screen shot 2016-09-15 at 1 28 36 pm" src="https://cloud.githubusercontent.com/assets/1418193/18566342/5d3dc8b4-7b48-11e6-875b-9efb0f71aac7.png">

**Comment by AdamStuart** [comment]
If "force single" is checked, change text:
Not all mappings one-to-one:
to
Some mappings reduced to first value:

**Comment by AdamStuart** [comment]
MappingUtil.createMsg:281
