### ISSUE TITLE
Command API does not conform to standards

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#24]
While reviewing all the commands for R functions, this one stood out as not fitting in, missing key args and inconsistent with UI.

Current args with example values:
`{
  "only_use_one": "true",
  "source_column": "name",
  "source_selection": "Ensembl",
  "species": "Yeast",
  "target_selection": "SGD"
}
`

Proposed:
`
{
  "columnName": "name",
  "forceSingle": "true",
  "network": "current",
  "mapFrom": "Ensembl",
  "species": "Yeast",
  "table": "galFiltered.sif default node",
  "mapTo": "SGD"
}
`

**Comment by AlexanderPico** [comment]
@AdamStuart Can you double check that the new args won't require any Cytoscape changes we should push into 3.6.1?

If not (as I suspect) can you also estimate when you can release the updated idmapper core app?

**Comment by AlexanderPico** [comment]
Can I test these via a new jar?

**Comment by AlexanderPico** [comment]
`networkName` does not seem to be working.

Steps to reproduce:

1. Open Yeast Perturbation.cys  (name="galFiltered.sif")
2. Clone Network (name="galFiltered.sif_1")
3. Select newly cloned network
4. Run command to perform ID mapping on __other__ networks, e.g,
```
idmapper map column columnName="name" mapFrom="Ensembl" mapTo="SGD" species="Yeast" networkName="galFiltered.sif"
```

Expected: Mapping should occur on the network named.
Obs: The mapping occurs on the currently selected network, ignoring the networkName parameter.

**Comment by AlexanderPico** [comment]
`table` also appears to be ignored. 

Looking at existing examples of commands, I realize that Scooter has a nifty solution here...  You should be able to copy/paste the `table` arg (and docs) from commands like `table list columns` (see screenshot). This arg takes __both__ network and table data, like "galFiltered.sif default node", so no need for a separate `networkName` arg. 

![screen shot 2018-02-16 at 3 58 27 pm](https://user-images.githubusercontent.com/1418193/36335110-61d764c4-1332-11e8-9b9c-6619a9581399.png)

**Comment by AlexanderPico** [comment]
So, it `table` works like so, then this command would be the one to test in the case described above:

```
idmapper map column columnName="name" mapFrom="Ensembl" mapTo="SGD" species="Yeast" table="galFiltered.sif default node"
```

This should map a column in the node table of galFiltered.sif _**even if galFiltered.sif_1 is selected**_

**Comment by AdamStuart** [comment]
Got it. I think I’ve been using the combined names (network and table) as the table name.

Adam
