### ISSUE TITLE
BridgeDb App: unable to add BioMart as a resource

### ISSUE THREAD

**Issue by jjgao** [cytoscape/idmapper#27]
![image](https://user-images.githubusercontent.com/840895/37682144-199a70fc-2c5f-11e8-9fb4-bfe9482349d4.png)

**Comment by AdamStuart** [comment]
![sourcetab](https://user-images.githubusercontent.com/7647213/39331625-ec3d3802-4959-11e8-951c-0e6b116f4ecd.png)
