### ISSUE TITLE
Empty error message

### ISSUE THREAD

**Issue by zhangch** [cytoscape/idmapper#28]
![screen shot 2018-03-20 at 22 48 46](https://user-images.githubusercontent.com/3987539/37693678-b8e77cc6-2c97-11e8-990c-c0f2332299fc.png)

When I right-click any non-ID column and chose "Map column...", it will pop-up an empty message dialog.

**Comment by AdamStuart** [comment]
NPE in JDialogTaskManager.execute (line 230)

**Comment by AdamStuart** [comment]
now shows a good error message, but after you close the dialog

**Comment by AdamStuart** [comment]
catching the error in MapColumnTaskFactory, ahead of the task
