### ISSUE TITLE
Missing Ensembl ID (import table from public databases)

### ISSUE THREAD

**Issue by zhangch** [cytoscape/idmapper#29]
![screen shot 2018-03-20 at 22 55 58](https://user-images.githubusercontent.com/3987539/37693790-792e50ea-2c98-11e8-9917-78abe35c460c.png)

It's base on galFiltered network.
When I tried to test "import table" function, I found there is no "Ensembl ID" under Data Type list. I don't know it is my own problem or I missed something.

**Comment by AdamStuart** [comment]
not idmapper in screen shot
