### ISSUE TITLE
Failed ID mapping Cytoscape

### ISSUE THREAD

**Issue by kscupakova** [cytoscape/idmapper#30]
Hello,
I am trying to map wikiPathway to ensemble ID so I can then visualize my data on it.
 I selected a column in the node table and click on map column. Choose homo sapiens, from entrez gene to ensemble .. after a while it returns a message: failed to map IDs. 

The same happens if I select the who network and go to apps --> BridgeDB--> select multiple id sources  ( entrez gene, ensemble, cheBi, HMDB) and source columns ( I tried the XrefDatasource as well as the actual name column) --> then I define output as ensemble. ( I also did the manage mapping ID resources where I used the web resources for human). Despite all that I end up with No ID mapped, check you id sources and mapping resources.

Any help will be greatly appreciated.
cheers,
Klara

**Comment by AdamStuart** [comment]
Klara,

Sorry this isn’t working for you.  Can you send me a data file to reproduce it?

Adam

**Comment by kscupakova** [comment]
Dear Adam,

Thank you for your quick reply. By playing around I found out it was my mistake why it didn’t map at all. Now I have different question.

If I do map ID via the app--> bridgeDb I get mapped only subset of IDs even though I did inserted all the possible IDs in the file. ( entrez gene, ensemble, uniport). If I do direct click on the column and say map column I get yet another subset of IDs mapped. Funnily, these are the exact opposite one that were not mapped by the app route.

Attached is a screenshot of what I am talking about. The data I am using is new network  that I imported from database --> wikipathways --> homo sapiens-->pathway metastatic brain tumor.

I hope you have sufficient info, if not please let me know.

Cheers,
Klara

**Comment by AdamStuart** [comment]
Klara,

I’m working on the Cytoscape Wikipathways app to unify ids upon import.  If the sources are mixed, it will add an Ensembl column, and do all the mappings.  Alex Pico and I talked about putting many to one mapping in idmapper, but this seemed like a better solution.

Will that take care of it for you?

Adam

**Comment by kscupakova** [comment]
Dear Adam,

That is good news.
Thanks again for your swift replies.

Regards,
Klara

**Comment by AdamStuart** [comment]
to be fixed in Wikipathways.  many-to-one mapping not supported here
