### ISSUE TITLE
Species-specific sources are wrong in 3.6.2

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#31]
Testing 3.6.2 jar:

1. Search and import WP1246
2. Map column: XrefId
3. Switch to "mouse"
Bug 1: ZFIN is in list, but ZFIN should only show up for zebrafish speceis

4. Pulldown source options
Bug 2: HGNC is in list, but that is only for human species. Mouse options (MGI) is missing.

**Comment by AdamStuart** [comment]
found TunableUIHelper and RequestsUIHelper classes
