### ISSUE TITLE
Fill New Column with name of To datasource

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#5]
By default, the new column should be named after the user-selected To datasource, e.g., "Ensembl" etc.

**Comment by AdamStuart** [comment]
Alex,

This version always names the resulting column with the target datasource.  See if you can come up with cases where that is not desirable.

I was not able to change the version by editing the POM, so I did it post facto.  Not sure how this is supposed to work.

Adam

**Comment by AdamStuart** [comment]
> Alex,
> 
> This version always names the resulting column with the target datasource.  See if you can come up with cases where that is not desirable.
> 
> I was not able to change the version by editing the POM, so I did it post facto.  Not sure how this is supposed to work.
> 
> Adam

This one has the version tag in the POM.

**Comment by AdamStuart** [comment]
Field for the target column name is gone.  Default is the target datasource name, with a numerical suffix to keep it unique.
