### ISSUE TITLE
Species should be remembered between uses and sessions

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#6]
Store species as a cytoscape property and fill this tunable with the value by default.

**Comment by AdamStuart** [comment]
kept in static variable, not in property yet.

**Comment by AlexanderPico** [comment]
Actually, this is a great solution. Often the preferred species changes across session, but rarely within a session. Let's instead consider a broader implementation for "preferred species" in the core, separate from this core app.
