### ISSUE TITLE
Guess the From datasource

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#7]
Bridgedb has the ability to guess the datasource. Use this to fill the From datasource value.

For example, even with a generic ID like "11234", bridgeDb can quickly tell you which possible matches. These can further be filtered for exact matches in this use case and often return just one possible hit:

http://webservice.bridgedb.org/Human/search/11234?limit=1

**Comment by AdamStuart** [comment]
resolved, but needs broader testing.  HGNC matches most everything, so it is a lower priority if another source matches equally well  (most out of first 10 entries)
