### ISSUE TITLE
New column should show up next to From column

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#8]
Currently, new columns are added to the end. This should probably be added to the Table API in general, i.e., the control for where a new column is added.

**Comment by AlexanderPico** [comment]
Implementing option in CreateColumn function in Cytoscape core in order to allow this feature for ALL PEOPLE

**Comment by AdamStuart** [comment]
Function not in API, and adding it proved complicated because there are layers of abstraction around the BrowserTableColumnModel.

**Comment by bdemchak** [comment]
Can you track this as a feature request in RedMine?
