### ISSUE TITLE
Discoverability

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/idmapper#9]
Adapted idea from Barry:  How about adding menu item to the "+" icon on the Table Panel, e.g., "New ID Column Mapped From >" which expands to a submenu list of column headers. When clicked, it brings up the ID Mapper dialog.

**Comment by AlexanderPico** [comment]
Attribute Browser toolbar does not have an API.  We cannot add to that toolbar until that API is added. Something to add to the feature work in the Cytoscape core.

There are hacky solutions that we should probably avoid.

**Comment by AdamStuart** [comment]
Suspending the issue until we prioritize changes to the tool bar
